# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a9bb19b0b79f2216a13fba6d7edd3b15fa398b92ae3fc953edb3f97f6bca6745b43c81c3eaeda17e35786e1dc6bcd5f16f76ba8264967c2a7ec4e7ad502786b

test:
  secret_key_base: 3bbf0ac31316f2339ca102ed16081849eb6bade0c29c98472903f62196a9b684a2565b6c2f5fac13f60506c0712ea4a93a2148899e84252d977d4f4efaf6a0e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
